<a href="https://colab.research.google.com/github/andrcvs/dio-lab-open-source/blob/main/notebooks/C%C3%A1lculo_de_M%C3%A9tricas_de_Avalia%C3%A7%C3%A3o_de_Aprendizado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarefa
Calcular as métricas de avaliação de modelos de classificação (acurácia, sensibilidade, especificidade, precisão e F-score) utilizando uma matriz de confusão arbitrária e as fórmulas correspondentes.

## Criar uma matriz de confusão

### Subtask:
Definir os valores para Verdadeiros Positivos (VP), Verdadeiros Negativos (VN), Falsos Positivos (FP) e Falsos Negativos (FN).


In [31]:
import numpy as np

# Gerar uma matriz de confusão arbitrária 10x10
# Esta matriz representa um cenário de classificação multiclasse
matriz_confusao_multiclasse = np.random.randint(0, 50, size=(10, 10))

print("Matriz de Confusão Multiclasse Gerada:")
print(matriz_confusao_multiclasse)

# Para calcular as métricas de classificação binária (acurácia, sensibilidade, etc.)
# precisamos de uma matriz 2x2 (VP, VN, FP, FN).
# Vamos simular a extração para uma classe específica (por exemplo, a primeira classe, índice 0)
# onde a classe positiva é a classe 0 e a classe negativa são todas as outras.

# Verdadeiros Positivos (VP): Elementos da diagonal principal para a classe 0
vp = matriz_confusao_multiclasse[0, 0]

# Falsos Negativos (FN): Soma dos elementos na linha da classe 0, exceto o VP
fn = np.sum(matriz_confusao_multiclasse[0, :]) - vp

# Falsos Positivos (FP): Soma dos elementos na coluna da classe 0, exceto o VP
fp = np.sum(matriz_confusao_multiclasse[:, 0]) - vp

# Verdadeiros Negativos (VN): Soma de todos os elementos, menos VP, FN e FP
total_elementos = np.sum(matriz_confusao_multiclasse)
vn = total_elementos - vp - fn - fp


print(f"\nValores Extraídos (simulando classificação binária para a classe 0):")
print(f"VP: {vp}")
print(f"VN: {vn}")
print(f"FP: {fp}")
print(f"FN: {fn}")

Matriz de Confusão Multiclasse Gerada:
[[47 11 21 27 26  4 35 31 31 16]
 [42 22 31 25 22 28 32 18 13 17]
 [10 43 28  1 17 45 13 10  3 15]
 [21 14 10 25 46 26 30 10 15 46]
 [20  5 38 27 38 23 49 20 45 46]
 [ 3  9 24 34 38 48 13 24 45  3]
 [27 43  6 42  3 33 13 44 37 31]
 [33 19 16 17 27 47  4  5 29 45]
 [ 3 45 37 13  5 38 34 29  3  9]
 [34  0 46 41 33  4 39 27 18 20]]

Valores Extraídos (simulando classificação binária para a classe 0):
VP: 47
VN: 2036
FP: 193
FN: 202


## Implementar funções para as métricas

### Subtask:
Criar funções em Python para calcular acurácia, sensibilidade (recall), especificidade, precisão e F-score com base nas fórmulas fornecidas na descrição da tarefa (que são as fórmulas padrão para essas métricas).


In [32]:
def calcular_acuracia(vp, vn, fp, fn):
  "Calcula a acurácia."
  total = vp + vn + fp + fn
  if total == 0:
    return 0.0  # Evitar divisão por zero
  return (vp + vn) / total

def calcular_sensibilidade(vp, fn):
  "Calcula a sensibilidade (recall)."
  denominador = vp + fn
  if denominador == 0:
    return 0.0  # Evitar divisão por zero
  return vp / denominador

def calcular_especificidade(vn, fp):
  "Calcula a especificidade."
  denominador = vn + fp
  if denominador == 0:
    return 0.0  # Evitar divisão por zero
  return vn / denominador

def calcular_precisao(vp, fp):
  "Calcula a precisão."
  denominador = vp + fp
  if denominador == 0:
    return 0.0  # Evitar divisão por zero
  return vp / denominador

def calcular_fscore(precisao, sensibilidade):
  "Calcula o F-score."
  denominador = precisao + sensibilidade
  if denominador == 0:
    return 0.0  # Evitar divisão por zero
  return 2 * (precisao * sensibilidade) / denominador

## Calcular as métricas

### Subtask:
Usar os valores definidos na matriz de confusão e as funções implementadas para calcular cada métrica.


In [33]:
acuracia = calcular_acuracia(vp, vn, fp, fn)
sensibilidade = calcular_sensibilidade(vp, fn)
especificidade = calcular_especificidade(vn, fp)
precisao = calcular_precisao(vp, fp)
fscore = calcular_fscore(precisao, sensibilidade)

## Exibir os resultados

### Subtask:
Apresentar as métricas calculadas em um formato claro e legível.


In [34]:
print(f"Acurácia: {acuracia}")
print(f"Sensibilidade: {sensibilidade}")
print(f"Especificidade: {especificidade}")
print(f"Precisão: {precisao}")
print(f"F-score: {fscore}")

Acurácia: 0.8405972558514931
Sensibilidade: 0.18875502008032127
Especificidade: 0.9134140870345446
Precisão: 0.19583333333333333
F-score: 0.19222903885480572
